---
title: "EATMINT1 experiment - Sharing emotions generates online adaptative collaborative acts - charts"
author: "Sunny Avry"
date: "November 27th, 2019"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


# Libraries
```{r}
library(xlsx); library(ggplot2); library(XML); library(reshape2); library(plyr)
```
# Data importation
```{r}
options(scipen=999) #remove scientific notation

results5 = read.xlsx("overall_results.xlsx", 1, header = TRUE) #results5 is the sheet for the results with a window size of 5 (cf. emotion.window.size in analysis.Rmd)
results5
```


# RTU5

# Interested

## Data preparation 
```{r}
#interested no emotion
interested.mean.no.emotion <- results5$interested_mean.no.emotion
names(interested.mean.no.emotion) <- collaborative.processes

interested.mean.no.emotion.sorted <- sort(interested.mean.no.emotion, decreasing = TRUE) #means for the emotion of interest in decreasing order
interested.mean.no.emotion.sorted

interested.mean.emotion <- results5$interested_mean.emotion

#interested emotion
interested.mean.emotion.sorted <- interested.mean.emotion[order(factor(names(interested.mean.emotion), levels = names(interested.mean.no.emotion.sorted)))] #the sorting is based on the sorting for interested no emotion. Names are kept in the same order
interested.mean.emotion.sorted

```

## Plotting

```{r}

```






















